server:
  port: 8080
database:
  - user: admin
    password: admin
    host: localhost
    dbName: shopTao
  - user: order
    password: order
    host: localhost
    dbName: order
security:
  jwt:
    key: abc123
